# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_A_joint
    - arm_B_joint
    - arm_C_joint
    - arm_D_link
    - grasper_joint
    - hand_left_joint
    - hand_left2_joint
    - hand_right_joint
    - hand_right2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_A_joint
      - arm_B_joint
      - arm_C_joint
      - arm_D_link
      - grasper_joint
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_left_joint
      - hand_left2_joint
      - hand_right_joint
      - hand_right2_joint